### ISSUE TITLE
docs.esotalk.org subdomain missing redirect 

### ISSUE THREAD

**Issue by tvb** [esotalk/docs#3]
![image](https://cloud.githubusercontent.com/assets/1263414/2980209/f8890dfc-dbe4-11e3-890a-26ba0f7cf927.jpg)

**Comment by tobyzerner** [comment]
Is some place linking to this? Otherwise I don't think it's necessary

**Comment by tvb** [comment]
Nope just stumbled upon by manual entering.
I do think it doesn't hurt to redirect or remove it as virtual host either way.
